parser: '@typescript-eslint/parser'
extends: 'plugin:@typescript-eslint/recommended'
rules:
  semi:
    - error
    - never
  quotes:
    - error
    - single
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/member-delimiter-style': off
