on:
  push:
    branches:
      - master

env:
  HOST: ${{ secrets.HOST }}
  USER: ${{ secrets.USER }}
  SSH_PK: ${{ secrets.SSH_PRIV_KEY }}
  DOCKER_USER: ${{ secrets.USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  SERVER_PORT: 1495

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare VM
        run: |
          sudo mkdir -p "/usr/local/bin/docker"
          sudo curl \
            -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo cat /etc/resolv.conf
      - name: Setup SSH
        run: |
          cd ~
          mkdir .ssh/
          echo $SSH_PK >> .ssh/id_rsa
          chmod 400 .ssh/id_rsa
          ssh-keyscan -H $HOST >> .ssh/known_hosts
      - name: Getting .env
        run: |
          scp "$USER@$HOST:~/dotenv/feedback_bot" .env
      - name: Build image
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker-compose build
          docker-compose push
      - name: Deploy
        env:
          DOCKER_HOST: "ssh://$USER@$HOST"
        run: |
          docker-compose pull
          docker-compose up -d
