name: CI

on:
  push:
    branches:
      - master

env:
  HOST: ${{ secrets.HOST }}
  USER: ${{ secrets.USER }}
  SSH_PK: ${{ secrets.SSH_PRIV_KEY }}
  DOCKER_USER: ${{ secrets.USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  SERVER_PORT: 1495
  COMPOSE_MAIN: docker-compose.yml
  COMPOSE_PULL: docker-compose.pull.yml

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Update packages
        run: |
          sudo mkdir -p "/usr/local/bin/docker"
          sudo curl \
            -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Setup SSH
        run: |
          mkdir ~/.ssh/
          echo "$SSH_PK" >> ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
      - name: Getting .env
        run: |
          scp "$USER@$HOST:~/dotenv/feedback_bot" .env
      - name: Build image
        run: |
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
          docker-compose -f $COMPOSE_MAIN -f $COMPOSE_PULL build
          docker-compose -f $COMPOSE_MAIN -f $COMPOSE_PULL push
      - name: Deploy
        env:
          DOCKER_HOST: "ssh://${{ env.USER }}@${{ env.HOST }}"
        run: |
          docker-compose -f $COMPOSE_PULL pull
          docker-compose -f $COMPOSE_MAIN -f $COMPOSE_PULL up -d
